### ISSUE TITLE
Unable to create clients that are "deleted" but no error received.

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#587] opened 2018-11-26 09:45 UTC
If a client is marked as deleted in the system, then the API will not return them.
However if you try to create a client that already existed once (e.g. via Fabrica), then you will receive no error which then causes you unable to know the client is deleted.

I'd suggest we actually do always show deleted clients in returned results,  but they have a status marked as deleted, they can also not then update/modify, i.e. they are "disabled".

**Comment by mfenner** [comment] 2018-11-26 10:05
Please see https://github.com/datacite/bracco/issues/54

**Comment by richardhallett** [comment] 2018-11-26 10:16
Potentially related to: https://github.com/datacite/lupo/pull/135

**Comment by kjgarza** [comment] 2018-11-26 16:56
the call from bracco is :https://api.datacite.org/clients?id=RADS.fie, this imply that Bracco is expecting the clients to exist in the database even when deleted. 

However, i cannot reproduce that error, I can see the message correctly 

![image](https://user-images.githubusercontent.com/1092861/49028571-fdcf0900-f1a2-11e8-8d31-d6b67306a6d2.png)

![image](https://user-images.githubusercontent.com/1092861/49029332-9f0a8f00-f1a4-11e8-8ebf-2a60106412c1.png)

**Comment by mfenner** [comment] 2018-12-04 13:46
Can't reproduce. Closing the issue.

**Closed** 2018-12-04 13:46 UTC
Labels: bug, needs review, wontfix
