### ISSUE TITLE
New usage events are not show in Eventdata even after submitting usage data

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#1384] opened 2021-12-01 15:31 UTC
### Expected Behaviour

When item is added in relatedIdentifier a new eventdata event must be created. The same should happen when a new usage report containing findbale dois is ingested. 

### Current Behaviour

Crossref has reported that since Oct 11th no new events have been generated in the share service eventdata. Looking at the eventdata monitor and the index we can also see that no new events of any type (usage, orcid, related, etc) have been generated since Nov 11th. https://observablehq.com/@kjgarza/9f4b8b4482076984

![image](https://user-images.githubusercontent.com/1092861/144247295-fd57aaf9-9e41-4d4d-80c0-bb17f82cc0cf.png)

also usage reports are not being show as reported by other users

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2pbx1)

### Steps to Reproduce

1. step1
2. step2
3. step3
4. step4

### Hypothesis

There might be JWT issues with Crossref TOKEN

![image](https://user-images.githubusercontent.com/1092861/144306150-52ed5592-403f-421f-ac63-51fbc8b86ef5.png)

https://app.datadoghq.com/logs?cols=%5B%22core_host%22%2C%22core_service%22%2C%22log_elb.performance.backend_processing_time%22%2C%22log_duration%22%5D&context_event=AQAAAWl631PIvQdt4wAAAABBV2w2MzJLLVNKc1F4SURrXzRKVg&event&from_ts=1635796993669&index=main&live=true&messageDisplay=inline&query=%40aws.awslogs.logGroup%3A%22%2Fecs%2Flevriero%22&stream_sort=desc&to_ts=1638388993669

**Comment by kjgarza** [comment] 2021-12-01 20:08
There might be JWT issues with Crossref TOKEN

![image](https://user-images.githubusercontent.com/1092861/144306150-52ed5592-403f-421f-ac63-51fbc8b86ef5.png)


 https://app.datadoghq.com/logs?cols=%5B%22core_host%22%2C%22core_service%22%2C%22log_elb.performance.backend_processing_time%22%2C%22log_duration%22%5D&context_event=AQAAAWl631PIvQdt4wAAAABBV2w2MzJLLVNKc1F4SURrXzRKVg&event&from_ts=1635796993669&index=main&live=true&messageDisplay=inline&query=%40aws.awslogs.logGroup%3A%22%2Fecs%2Flevriero%22&stream_sort=desc&to_ts=1638388993669

**Comment by eunices** [comment] 2021-12-09 01:58
Hi, we're interested to have this issue fixed. 

The [counter-processor](https://github.com/CDLUC3/counter-processor/releases/tag/v0.0.1 ) script is used to submit views/downloads statistics, as part of [Dataverse's Make Data Count](https://guides.dataverse.org/en/latest/admin/make-data-count.html). It sends a POST request to Datacite /reports API endpoint.

However, the bug exists such that the /events endpoint for a DOI is not populated with "datacite-usage" for "source-id" key, upon 200/201 status code for POST request to /reports.

**Comment by kjgarza** [comment] 2021-12-16 06:00
FYI suddenly events seem to have been started being created again (from Dec 15)
![image](https://user-images.githubusercontent.com/1092861/146316491-1277daae-7266-40b4-8916-4371f61dec72.png)

**Comment by kjgarza** [comment] 2021-12-17 17:38
@MaryHirsch I think this one is fixed now. It was a wrong token

**Comment by kjgarza** [comment] 2021-12-17 17:46
@MaryHirsch I think this one is fixed now. It was a wrong token

**Comment by MaryHirsch** [comment] 2022-01-05 11:25
The DataCite member confirmed that this is working. I think this can be closed @svogt0511 ?

**Comment by svogt0511** [comment] 2022-01-10 14:51
@maryhirsch, I will close this. I believe there were 2 problems. The first a was token problem, as Kristian mentioned early on in the ticket. Richard fixed that and usage data started being forwarded. There was another related problem, issue #1414, which Richard fixed, as well. So in short, we are all set on this and I will close it.

--- original message ---
On January 5, 2022, 6:25 AM EST ***@***.*** wrote:



The DataCite member confirmed that this is working. I think this can be closed @svogt0511 ?

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you were mentioned.Message ID: ***@***.***>
--- end of original message ---

**Closed** 2022-01-10 14:52 UTC
Labels: bug
