### ISSUE TITLE
zenodo DOIs do not provide x-bibtex rendering

### ISSUE THREAD

**Issue by yarikoptic** [datacite/datacite#129] opened 2017-06-22 21:07 UTC
NB not sure if that is the correct repository to complain against, so please pardon if misfiled

whenever redirect works for pdf
```shell
$> curl https://data.datacite.org/application/pdf/10.5281/zenodo.60847
<html><body>You are being <a href="http://zenodo.org/record/60847">redirected</a>.</body></html>%    
```
bibtex entries do not work
```shell
$> curl https://data.datacite.org/application/x-bibtex/10.5281/zenodo.60847
The resource you are looking for doesn't exist.
```
whenever they work for other, non-zenodo, items
```shell
$> curl https://data.datacite.org/application/x-bibtex/10.5284/1015681     
@article{https://doi.org/10.5284/1015681,       
  doi = {10.5284/1015681},
  author = {{Archaeological Project Services}},
  keywords = {Archaeology, Grey Literature},
  language = {en},
  title = {Excavation of a Romano-British Cemetery at the water treatment plant, Saltersford, Grantham, Lincolnshire},
  publisher = {Archaeology Data Service},
  year = {1995}
}
```

**Comment by yarikoptic** [comment] 2017-06-22 21:24
the issue is not localized to zenodo -- other entries seems to be impaired too:
```shell
$> curl https://data.datacite.org/application/x-bibtex/10.1038/nrd842                    
The resource you are looking for doesn't exist.%  
```
and it used to work just fine IIRC.

**Comment by mfenner** [comment] 2017-06-22 21:34
@yarikoptic this is a bug and I will look into it. The problem is with parsing the DataCite XML, so content negotiation is generally broken for that DOI. `application/pdf` only works, because it is not supported and thus ignored.

**Comment by mfenner** [comment] 2017-06-22 21:48
Thanks for raising this. The error was caused by a broken DataCite service to look up the DOI registration agency from the prefix (https://api.datacite.org/prefixes/10.5284, DataCite in you first example, Crossref in your second example). We did some configuration changes of our proxy servers today and that accidentally broke the prefix lookup.

All is fixed now and your examples work for me.

**Closed by mfenner** 2017-06-22 21:48 UTC
Labels: bug, create

**Comment by yarikoptic** [comment] 2017-06-22 23:44
@mfenner THANK YOU very much for super fast resolution! Seems to be working for me now as well.

**Comment by datacite-support** [comment] 2017-06-23 04:00
THANK YOU for alerting us to this issue.
