### ISSUE TITLE
New password is visible after following the set password link from an automated email

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1454] opened 2022-03-07 13:18 UTC
#### Expected Behaviour

When a user enters a new password it is hidden

#### Current Behaviour

When a user enters a new password after following the set password link from an automated email, it is visible

#### Steps to Reproduce

Reset password
Click on link in automated email
Type a new password into the set password box
The password is visible

### Context (Environment)

Fabrica

#### Possible Implementation

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2rsyd)

**Comment by svogt0511** [comment] 2022-03-07 22:16
@MaryHirsch I took this because when I saw the report I knew what it was.

**Comment by kjgarza** [comment] 2022-03-09 10:42
can't reproduce  @MaryHirsch @svogt0511 , can you double check ??
![image](https://user-images.githubusercontent.com/1092861/157425760-58738feb-05fa-43d4-a26b-4ca88bb001da.png)

**Comment by digitaldogsbody** [comment] 2022-03-09 10:59
The fix was deployed this morning with https://github.com/datacite/bracco/releases/tag/3.9.40

**Comment by kjgarza** [comment] 2022-03-09 11:14
Thanks 👍  I got it as a new feature request... but I thought this was already done. We just did everything too fast 🤣  Thanks @svogt0511

**Comment by svogt0511** [comment] 2022-03-09 13:54
The issue is usually closed automatically when the fix is merged.  Closing it now.

**Closed** 2022-03-09 14:21 UTC
Labels: bug
