### ISSUE TITLE
Sentry is unavailable for bug tracking

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#853] opened 2019-10-07 13:56 UTC
Due to the number of bugs being sent to Sentry this is causing Sentry to overexceed limits and therefore prevents all bug fixing.

The main target appears to be bracco is being very noisy with errors that are raised to Sentry.

**Comment by mfenner** [comment] 2019-11-21 14:27
Not a bug, closing.

**Closed by mfenner** 2019-11-21 14:27 UTC
Labels: Backlog

**Comment by richardhallett** [comment] 2019-11-21 14:33
This is still an issue, sentry was unavailable again just last week due to too many requests.
I think we need to handle removing so many requests going to Sentry. But I guess this can be handled on specific repositories, I raised this issue for us to be aware and try and deal with it in some way.
