### ISSUE TITLE
Findable DOIs not resolving

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#961] opened 2020-02-12 11:28 UTC
**Describe the bug**

DOIs not resolving even though they are in findable state

https://doi.org/10.21257/sg.119
https://doi.org/10.26039/2xtw-y269
https://doi.org/10.26039/1k21-4488
https://doi.org/10.26039/6qf1-0e35

**To Reproduce**

e.g https://doi.datacite.org/dois/10.21257%2Fsg.119
10:41 AM
https://doi.org/10.21257/sg.119
10:43 AM
and https://doi.datacite.org/dois/10.26039%2F2xtw-y269
10:43 AM
https://doi.org/10.26039/2xtw-y269

**Desktop (please complete the following information):**

Fabrica production

**Comment by richardhallett** [comment] 2020-02-12 12:31
Not a bug, this is a special handling for ETHZ who manage their own DOI registration.

**Comment by mfenner** [comment] 2020-02-13 15:43
ETHZ is no longer using their own handle server. The issue was resolved via https://github.com/datacite/lupo/issues/414.

**Closed by mfenner** 2020-02-13 15:43 UTC
Labels: bug
