### ISSUE TITLE
Consortium unable to view Repositories

### ISSUE THREAD

**Issue by daslerr** [datacite/datacite#869] opened 2019-11-01 07:25 UTC
The IRLCO Consortium cannot see the Repository TUDUBLIN.ARROW in their list of Repositories, even though TUDUBLIN is one of their Consortium Organizations. Other Repositories appear correctly in the list. 

I checked the TUDUBLIN account, and it was not showing a parent Consortium in its settings (similar to #858), even though the account was visible in IRLCO's list of Consortium Organizations. I updated TUDUBLIN's settings to contain the parent Consortium information, but this changed nothing. TUDUBLIN.ARROW still does not show in the list of Repositories for IRLCO. 

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_11sn7)

**Comment by mfenner** [comment] 2019-11-04 21:00
Duplicate of datacite/datacite#858.

**Comment by mfenner** [comment] 2019-11-05 10:53
Reopening, as this is a separate issue.

**Comment by mfenner** [comment] 2019-11-27 20:09
Can't reproduce after recent code changes.

**Closed** 2019-11-27 21:40 UTC
Labels: bug
