### ISSUE TITLE
Salesforce Fabrica DOI Numbers Synchronization

### ISSUE THREAD

**Issue by brittadreyer** [datacite/datacite#1317] opened 2021-07-30 15:26 UTC
The DOI numbers of the registered and findable DOIs are not synchronizing with Salesforce (probably since July 14th, when Martin reset the password). Here is an example of a consortium organization, who has registered findable DOIs on July 19th (this should have been synched by now) https://doi.datacite.org/providers/ruwk/dois but the Salesforce record was last updated on July 14th https://datacite.lightning.force.com/lightning/r/Account/0016N000003NosMQAS/view.

**Comment by svogt0511** [comment] 2021-07-30 19:58
It turns out that updating the providers is not enough.  Their repositories have to be updated which will cause the providers/organizations to report the correct numbers.  

Running the salesforce update job for organizations that changed during the period the update was out should correct things.

**Comment by mjbuys** [comment] 2021-07-31 04:00
@svogt0511 do you mean running the chron job for repositories?

**Comment by svogt0511** [comment] 2021-07-31 04:34
Pretty much, yes.

**Comment by svogt0511** [comment] 2021-07-31 04:37
Just let it run o er the entire set of repositories.

**Comment by svogt0511** [comment] 2021-08-02 13:04
If Britta is happy that she is seeing the correct data for billing I will just leave things as they are and update only on an as-needed basis.

**Comment by mjbuys** [comment] 2021-08-02 14:02
@svogt0511 For clarity, we need all repositories to have accurate DOI numbers as we report to consortium leads and provide members with fee estimated based on this. In addition, our SF dashboards use this information to build financial projections for next year. 

Will the daily job update all organizations and repositories?

**Comment by svogt0511** [comment] 2021-08-02 14:16
@mbuys The daily job updates organizations and repositories that have had changes over the past day.

**Comment by svogt0511** [comment] 2021-08-03 13:25
I ran the sync job for all repositories. The daily sync job is working so we should be good going forward.  Closing this issue.

**Comment by svogt0511** [comment] 2021-08-06 15:30
Reopening this issue.  There are still several items that need to be addressed.

See the Slack discussion in #salesforce starting [here](https://datacite.slack.com/archives/CJZGP3PE2/p1627650342001700).

- The yearly DOI totals calculation needs to be based on date registered so they fall into the correct year.
- The sync job seems to be running successfully every day as indicated by the [DataDog log](https://app.datadoghq.com/logs?query=%40aws.awslogs.logGroup%3A%22%2Faws%2Flambda%2Fupdate-salesforce-daily%22&index=%2A&from_ts=1626873746133&to_ts=1627478546133&live=true).  However, Britta has been receiving emails from Salesforce indicating that a CPU timeout has been occurring during the processing of the sync jobs.  See the screengrab, below.  Britta said that 

> Generally, they come it multiple times per day starting at 12:27 (CET). The following emails  come in at XX:27 e.g. 14:27 and  15:27. Yes, hopefully the Salesforce error ID is helpful.

- Billing data sync needs to happen if there is billing data in Fabrica, regardless of  'joined' field in the Fabrica DB. The date joined check should be removed so this can happen. 



![image](https://user-images.githubusercontent.com/4681304/128534508-497db59a-bfab-44f4-9035-0b539ae85c92.png)

**Comment by svogt0511** [comment] 2021-08-06 18:30
I just took a quick look at a CPU timeout email message that Britta is getting.  I have a couple of notes.  

It looks like the timeouts may not be related to the salesforce sync job that we have implemented to move data from Fabrica to Salesforce.  This looks more like it is related to an app called JustOn that we use in Salesforce for billing and invoicing.  The timeout is coming from one of their jobs which is perhaps launched automatically every day.  This would explain why Britta receives the timeout emails every day.

If there is high resource usage within a transaction, it is conceivable that the CPU time limit could be reached, especially if an entire job is considered a 'transaction'.  For example, if we are building invoices for 1000 customers in one job, it may need more than our allotted time to build that many invoices.  If that is the case, a solution might be to break up the job into several jobs.

Also the error mentions 'Apex'.  I don't think DataCite has written any of its own Apex code.

**Comment by mjbuys** [comment] 2021-08-06 18:35
Thanks @svogt0511. @brittadreyer this is likely a chain effect, as one the organizations are updated then the JustOn processes are triggered. Should we revert back to them again? 

@svogt0511 we have apex code for some of the customization work that we did for consortia and billing workflows.

**Comment by svogt0511** [comment] 2021-08-06 18:53
One last note.  I read that the CPU time limit for synchronous transactions is 10 seconds vs asynchronous transactions is 60 seconds.  We might be able to take advantage of that.

**Comment by svogt0511** [comment] 2021-08-11 16:51
Meeting notes [here](https://docs.google.com/document/d/1LmOG0aMyHrINRsx6iOUvtpKy7Z1M8s4EzBTLkzMQCNM/edit#heading=h.uib2fwr67ey5).  See 'Action Items'.

Example to illustrate the DOI count issue: [Fabrica counts](https://doi.stage.datacite.org/repositories/datacite.skv/dois) use year registered, [Salesforce counts](https://datacite--sync.lightning.force.com/lightning/r/Repositories__c/a1D9E000002n48NUAQ/view) use year created.  

![image](https://user-images.githubusercontent.com/4681304/129069953-fe1f0b6d-3986-422a-bb20-b626706a4fb9.png)


![image](https://user-images.githubusercontent.com/4681304/129070074-3c5ddf63-a6fa-4f68-8289-188592522910.png)

@mjbuys - the third item should be fixed in production.  Billing info still wasn't being sync'ed if date joined was null in Fabrica.  I removed that check and so billing data should be synced correctly now.  I tested it in stage.  If you find there are still errors, let me know, but I am pretty sure it is fixed now.

**Comment by svogt0511** [comment] 2021-09-22 16:23
More information on this.  I added some logging to make sure the correct DOI count was being pushed to Salesforce from Fabrica, and then checked Salesforce to make sure the repositories were being updated with that info.  There was only one repository updated today that had useful information: CRUI.UNITS.  The sync job ran successfully.  Information was collected and successfully passed to salesforce and the CRUI.UNITS repository was successfully updated in salesforce. 

That being said, at the time I checked Fabrica and the database, there was a discrepancy in the DOI count of about 100 DOIS.

It turns out, the DOI count that was passed to salesforce by the sync job was almost 100 less than the DOI count reported in Fabrica (see the screenshots, below).  There were a number of DOIs being created and updated around the time that the sync job was run and I am wondering if they were missed because they were updated after the sync job ran.

Given that, they should be picked up by tomorrow's sync, but I am not sure that is happening as it should owing, perhaps to 
some kind of timing miscalculation.

I am going to look into how mods are picked up based on time created/modified.  I am also going to extend the range of time the sync job looks for modifications in hopes that this will fix the problem and check tomorrow to see what happens with this job.  When the problem is fixed I will remove the extra logging and we should probably run a job that updates all repositories to catch ones that won't be fixed by the sync job.

SCREENSHOTS

DOI TOTALS FORWARDED BY THE SYNC JOB TO SALESFORCE:

![C64C8442-438B-4AD2-BF03-72AA8EB05A20](https://user-images.githubusercontent.com/4681304/134383247-6f36f2fe-2e79-40ea-b715-c1f67198d998.png)


DOI TOTALS REPORTED BY FABRICA FOR CRUI.UNITS:

![04DBBAA3-9089-44D1-839F-CE590BA0ED93](https://user-images.githubusercontent.com/4681304/134383121-cbf617ae-fb81-4aa2-8330-dd915c9434ec.png)

**Comment by svogt0511** [comment] 2021-09-22 17:21
I wanted to add some notes about item #3 in this [document](https://docs.google.com/document/d/1LmOG0aMyHrINRsx6iOUvtpKy7Z1M8s4EzBTLkzMQCNM/edit#heading=h.uib2fwr67ey5) - CPU timeouts.

Britta receives one or more emails daily reporting a CPU Timeout that occurs during some salesforce job that runs at various times during the day.  These emails can arrive one or more time during the day and seem to have no relationship to the timing of the sync job.  

I think the CPU Timeout problem is a totally separate issue from any problems associated with the sync job which updates DOI totals in repositories.  

I set up to receive emails whenever there is an unhandled exception in Apex application.  At the same time that Britta gets an email with the subject 'WG: Error Occurred During Flow "JustOn: Set Template on Invoice": Apex CPU time limit exceeded', I get an Apex Application 'unhandled exception CPU time limit exceeded' email (see the screenshot below).

The email is from a Salesforce application called Campaign Monitor.  It indicates a problem syncing an 'Email Opt Out' field from Campaign Monitor to Salesforce.    

UNHANDLED EXCEPTION EMAIL

![image](https://user-images.githubusercontent.com/4681304/134390560-798dfded-f68e-451a-8ae0-b86e2906ebd0.png)

**Closed** 2021-11-02 16:14 UTC
