### ISSUE TITLE
[REGRESSION] DOI content negotiation stopped working for DataCite DOI

### ISSUE THREAD

**Issue by dhimmel** [datacite/datacite#187] opened 2017-08-04 16:08 UTC
Currently the following query returns: `The resource you are looking for doesn't exist.`

```
curl --location --silent \
  --header "Accept: application/vnd.citationstyles.csl+json" \
  https://doi.org/10.7287/peerj.preprints.3100v1
```

It worked yesterday. Builds [are failing](https://travis-ci.org/greenelab/manubot/builds/261060859#L1558).

**Comment by dhimmel** [comment] 2017-08-07 21:57
The DOI Content Negotiation command now works.

I'm going to leave this open until closed by a maintainer, in case this issue was indicative of a more widespread issue. It does seem odd that content negotiation would work, then start failing, and then resume working. It's also worth noting that not all DataCite DOIs failed negotiation... so it wasn't a complete outage or something.

Tagging @mfenner.

**Comment by mfenner** [comment] 2017-08-07 22:40
@dhimmel I did some work on content negotiation over the weekend. It covered a number of issues, and I am not sure yet what was causing your particular problem. I will look into this, but it is good to know that your part is working again.

**Comment by mfenner** [comment] 2017-12-08 07:31
Closing the issue. The inconsistent behaviour was caused by issues with our Solr index, which was removed as a dependency one month ago.

**Closed by mfenner** 2017-12-08 07:31 UTC

**Comment by dhimmel** [comment] 2017-12-21 20:18
@mfenner I'm currently getting a similar issue where the query above returns `Resource not found.`

![resource-not-found](https://user-images.githubusercontent.com/1117703/34273408-36aaebc4-e662-11e7-8ad5-d3dbdf050357.png)

**Comment by mfenner** [comment] 2017-12-21 20:58
@dhimmel the underlying issue here is different: PeerJ has moved their DOIs to Crossref a week ago, and maybe they are not all re-registered with Crossref. Nothing DataCite can do, as this goes to the Crossref content negotiation now.

**Comment by dhimmel** [comment] 2017-12-21 21:08
> PeerJ has moved their DOIs to Crossref a week ago

Interesting. I didn't realize it was possible to migrate registration agencies for existing DOIs.

**Comment by mfenner** [comment] 2017-12-21 21:11
It is an unusual event, we have this every few months at DataCite. Crossref started allowing DOIs for preprints about a year go, makes sense for PeerJ to get all their DOIs from one place.

**Comment by mfenner** [comment] 2017-12-21 21:12
Normally content negotiation shouldn't be affected by this, I will investigate.

**Comment by michaelstoner** [comment] 2018-01-13 15:04
@dhimmel @mfenner please accept my apology about the delay in our re-registering of the metadata associated with the prefix move from Ezid & DataCite to CrossRef.  The preprints have been re-registered. 10 Preprints will require manual intervention, next week, as the new metadata is a super set of the previous metadata, we have moved from Dublin Core to CrossRef version 4.4.1.

**Comment by mfenner** [comment] 2018-01-13 15:45
Thanks for the update @michaelstoner!
