### ISSUE TITLE
Links to DataCite Commons do not display the query does not appear in the query field

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1275] opened 2021-05-31 15:38 UTC
#### Expected Behaviour

Clicking on a link to DataCite Commons with a query displays the query in the query field on the page

#### Current Behaviour

The query is not shown in the query field

#### Steps to Reproduce

1. DataCite Search shows expected behaviour https://search.datacite.org/works?query=coronavirus+AND+publicationYear%3A%3C2019
2. DataCite Commons does not show the query https://commons.datacite.org/doi.org?query=coronavirus+AND+publicationYear%3A%3C2019

### Context (Environment)

DataCite Commons

**Comment by richardhallett** [comment] 2022-08-26 11:29
This works as expected, possible fixed in unrelated PR. Closing as can't reproduce.

**Closed by richardhallett** 2022-08-26 11:29 UTC
Labels: bug
