### ISSUE TITLE
IsCitedBy creates reference instead of citation

### ISSUE THREAD

**Issue by lizkrznarich** [datacite/datacite#1416] opened 2021-12-20 14:16 UTC
### Describe the bug
Our docs show that adding a related identifier (ex, a DOI for an article) with relationType IsCitedBy to a  dataset DOI should create a citation. https://support.datacite.org/docs/contributing-data-citations . We have recent cases where IsCitedBy relationships are being counted as references rather than citations in REST API responses. This causes inaccurate citation counts in Commons, Search and the MDC widget. 

#### Expected Behaviour
Related identifiers with an IsCitedBy relationType appear in citations section of REST API response.

#### Current Behaviour
Related identifiers with an IsCitedBy relationType appear in references section of REST API response.

#### Steps to Reproduce
1. Update an existing DOI with a related identifier via the REST API or Fabrica, ex data:
```
{
  "data": {
    "attributes": {
      "relatedIdentifiers": [
        {
          "relationType": "IsCitedBy",
          "relatedIdentifier": "10.1016/j.joule.2021.09.015",
          "relatedIdentifierType": "DOI"
        }
      ]
    }
  }
}
```
2. Retrieve the DOI with the REST API, ex ```curl https://api.datacite.org/dois/10.7302/pa3f-4w30```
3. Related ID appears in relatinships.references, ex:
```
"references" : {
            "data" : [
               {
                  "id" : "10.1016/j.joule.2021.09.015",
                  "type" : "dois"
               }
            ]
         }
```

### Context (Environment)
Reported by member University of Michigan in production. Issue if affecting several DOIs, including:
10.7302/z23r0r29
10.7302/pa3f-4w30

#### Possible Implementation

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2qbv9)

**Comment by kjgarza** [comment] 2022-01-20 10:23
potentially related to https://github.com/datacite/lupo/issues/752

**Comment by mutanthumb** [comment] 2022-01-21 15:39
FYI, I noticed that Dryad is processing theirs with "Cites".  

Once this issue is resolved I plan to update all of our DOIs (400-500) that have related papers/articles using this process. I would be happy to test this for you.

**Comment by digitaldogsbody** [comment] 2022-04-25 13:17
The cause of this issue has been identified and a fix is currently in testing.

A DataCite Blog DOI affected by the fix was updated to add a "Cites" relation to another DataCite blogpost and the event data was correctly processed, and shows up in the source as a reference:
![source-cites](https://user-images.githubusercontent.com/93522067/165093008-e4b2de3c-7f50-4e3a-9904-3e25a7079834.png)

And the target as a citation:
![target-cites](https://user-images.githubusercontent.com/93522067/165093017-506c8001-5619-4a60-90a4-19156ecc5827.png)

Once the fix has been validated, it will be rolled out for all DOIs.

**Comment by mutanthumb** [comment] 2022-04-25 14:46
This is great news!! Thanks, susan

**Comment by digitaldogsbody** [comment] 2022-05-16 19:33
The fix for this has now been deployed to production - new relationships added using Cites or IsCitedBy should now show up correctly as a Reference or Citation respectively.

There is still work to do to clean up historic data which was processed before the fix was deployed, and this will be scheduled in the future. If you notice this issue affecting your records, please email support@datacite.org

**Closed** 2022-07-04 11:29 UTC
Labels: bug
