### ISSUE TITLE
Fabrica not displaying mathematical formulas that contain special characters (written in LaTex) correctly

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1206] opened 2021-02-10 14:24 UTC
#### Expected Behaviour

Fabrica correctly displays mathematical formulas that contain special characters (written in LaTex)

#### Current Behaviour

Fabrica not displaying mathematical formulas that contain special characters (written in LaTex) correctly

#### Steps to Reproduce

Correct: 
https://search.datacite.org/works?query=10.23638%2Fdmtcs-22-4-13+
The LexCycle on P 2 ∪ P 3 -free Cocomparability Graphs

Incorrect: https://doi.datacite.org/dois/10.23638%2Fdmtcs-22-4-13 
The LexCycle on $\overline{P_{2}\cup P_{3}}$-free Cocomparability Graphs

### Context (Environment)

Production

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2oemt)

**Comment by mfenner** [comment] 2021-02-19 14:27
This is a feature request. And duplicate of datacite/bracco#86.

**Comment by kjgarza** [comment] 2021-02-22 13:17
:wave: @MaryHirsch, we are tracking user stories in productboard. We have moved this issue there https://app.productboard.com/ .

**Closed by kjgarza** 2021-02-22 13:17 UTC
Labels: duplicate, enhancement, to_productboard
