### ISSUE TITLE
Affiliation information not appearing in REST API response

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#1018] opened 2020-05-11 08:47 UTC
### Expected Behaviour

The complete Affiliation block with ROR identifiers appears in API response

### Current Behaviour

The complete Affiliation block with ROR identifiers is not available through the JSON DOI API endpoint, e.g. https://api.datacite.org/dois/10.7907/F46C-3V67 although it does appear in the Fabrica JSON format tab and elsewhere in DataCite systems https://doi.datacite.org/dois/10.7907%2Ff46c-3v67

### Steps to Reproduce

1. https://api.datacite.org/dois/10.7907/F46C-3V67
2. https://doi.datacite.org/dois/10.7907%2Ff46c-3v67

### Context (Environment)

Production

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2nqdx)

**Comment by MaryHirsch** [comment] 2020-05-12 08:32
Further comments from user  And confusing enough is that for the same doi above the UI's download endpoint (https://search.datacite.org/works/10.5061/dryad.r6209 > download:datacite-json) gives the json data of that dataset in datacite schema v4.3 (https://api.datacite.org/dois/application/vnd.datacite.datacite+json/10.5061/dryad.r6209, note the affiliations json objects)
 
How come there is this discrepancy? Shouldn't it be the same data for both /dois and /dois/application responses?

**Comment by mfenner** [comment] 2020-05-12 08:41
This is intentional behaviour, as this would be a significant breaking change to the REST API.

**Comment by richardhallett** [comment] 2020-05-19 09:24
Closing as breaking change and working as intended.

**Closed by richardhallett** 2020-05-19 09:24 UTC
Labels: bug
