### ISSUE TITLE
Curl commands to content negotiation not returning expected citation styles

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/datacite#686] opened 2019-03-05 12:57 UTC
Expected Behaviour

send an api call to the content negotiation service data.datacite.org returns a response in the requested citation format

Steps to Reproduce

Example DOI: 10.6084/m9.figshare.7408460 

The following calls return exactly the same response:

```

curl -LH "Accept: text/x-bibliography; style=apa" https://doi.org/10.6084/m9.figshare.7408460

```

```
curl -LH "Accept: text/x-bibliography; style=mla" https://doi.org/10.6084/m9.figshare.7408460

```

Response 1 apa
Ahrweiler, P., Gilbert, N., Schrempf, B., Grimpe, B., &amp; Jirotka, M. (2018). The role of civil society organisations in European responsible research and innovation. Figshare. https://doi.org/10.6084/m9.figshare.7408460

Response 2 mla
Ahrweiler, P., Gilbert, N., Schrempf, B., Grimpe, B., &amp; Jirotka, M. (2018). The role of civil society organisations in European responsible research and innovation. Figshare. https://doi.org/10.6084/m9.figshare.7408460

Response from crosscite https://citation.crosscite.org/ for same DOI

1 apa
Ahrweiler, P., Gilbert, N., Schrempf, B., Grimpe, B., & Jirotka, M. (2018). The role of civil society organisations in European responsible research and innovation. Figshare. https://doi.org/10.6084/m9.figshare.7408460 

2 mla
Ahrweiler, Petra, et al. The Role of Civil Society Organisations in European Responsible Research and Innovation. Figshare, 2018, doi:10.6084/m9.figshare.7408460. 

Context (Environment)
Content negotiation data.datacite.org 

Hypothesis

Detailed Description

Possible Implementation

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_hpgr)

**Comment by mfenner** [comment] 2019-03-11 06:13
Duplicate of crosscite/content-negotiation#76.

**Comment by MaryHirsch** [comment] 2019-03-11 10:37
comments from the user that reported this "I've noticed that the Crosscite citation formatter doesn't actually directly use the endpoints from the documentation. Instead, it's calling its own /format endpoint (like https://citation.crosscite.org/format?doi=10.1145%2F2783446.2783605&style=apa&lang=en-US).

I'm also using this undocumented endpoint in our application now (which feels a bit hacky but works fine). Please let me know when the doi.org endpoints are fixed, so we can switch back to the documented way of implementation."

**Comment by richardhallett** [comment] 2019-10-15 12:32
I looked into this some more.
The answer to this might be more in relation to how content negotiation is handled going forward. As the new data.crosscite.org content negotiation seems to work differently.
Need confirming how we should handle sending additional parameter like the "style" going forward.

i.e. do we allow params in content type like: "text/x-bibliography; style=apa" for specific styling, or should people request the styling instead directly from the crosscite url using a query param of ?style=

**Comment by mfenner** [comment] 2020-01-21 07:12
Fixed this by supporting the style (and locale) in the content negotiation header, e.g. `text/x-bibliography; style=ieee`.

**Closed** 2020-01-21 10:31 UTC
Labels: bug
