### ISSUE TITLE
Events not created when DOI first created in registered or draft state

### ISSUE THREAD

**Issue by KellyStathis** [datacite/datacite#1710] opened 2023-01-19 16:53 UTC
### Describe the bug

When a DOI is created in registered or draft state and later changed to findable state, events are not created. This means that ORCID auto-update is not triggered and citations are not counted.

#### Expected Behaviour

Event creation (and therefore ORCID auto-update) should trigger when the DOI is in findable state, if there are ORCID iDs in the nameIdentifier field.

#### Current Behaviour

This DOI was https://doi.org/10.5438/b6wg-2530 created January 19, 2023 at 16:33:07 UTC in Registered state with ORCID iDs for myself (https://orcid.org/0000-0001-6133-4045) and Paul (https://orcid.org/0000-0003-4448-3844).

It was changed to Findable state at 16:50:30 UTC. No ORCID auto-update notification was received by either of us.

A similar issue was observed on January 10 with the blog post for the schema 4.4 API release. For this post, a similar workflow was followed and ORCID auto-update was not triggered for either me or @digitaldogsbody . However, when the DOI was subsequently updated *with no changes* by @richardhallett via the file upload, I received a notification. 

#### Steps to Reproduce

1. Create DOI in registered state with ORCID iDs in nameIdentifier
2. Change DOI to Findable state with no other metadata changes

#### Screenshots

n/a

#### Further details

Blog DOIs are created using Fabrica.

#### Hypothesis

I think a state change should trigger ORCID auto-update if there is a nameIdentifier present. However, the trigger may not be looking for metadata that was previously added in Registered state.

It's worth investigating whether this is also the case with changing state from Draft -> Findable.

#### Possible Implementation

n/a

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5m5cl)

**Comment by digitaldogsbody** [comment] 2023-01-30 20:38
I believe the hypothesis to be correct - following this logic:

* ORCID claiming is done by the Profiles service, but it is triggered by Levriero (aka event data)
* This worker runs watching the lupo_import queue: https://github.com/datacite/levriero/blob/master/app/workers/doi_import_worker.rb
* Anything in the queue goes through the `parse_record` function
* That function takes all name identifiers and pushes them to the name identifier processor: https://github.com/datacite/levriero/blob/2ee23e3ed044c3e08ab012133b0eeeb07d5a49d8/app/models/concerns/importable.rb#L256-L270
* This is where the claim data gets created and pushed to the profiles service: https://github.com/datacite/levriero/blob/2ee23e3ed044c3e08ab012133b0eeeb07d5a49d8/app/models/name_identifier.rb#L154-L181
* So Profiles will only know to make a claim if a DOI is either manually claimed, or goes through this automatic process
* The automatic process is only triggered in very specific circumstances:
  * https://github.com/datacite/lupo/blob/master/app/models/concerns/indexable.rb#L23-L34
  * On create or update of a model in Lupo - if that model is a `DataciteDoi` or `OtherDoi` AND there has been a change to either `related_identifiers` or `creators` or `funding_references` AND the state is `findable`

The practical upshot of this is (as far as I can tell) that if you create a DOI in draft or registered, and then the only change you make is to turn it findable, it will not go into the queue and ORCID auto-claims will not get triggered (and also various other event data changes will not happen / events wont be created)

**Comment by KellyStathis** [comment] 2023-10-12 16:41
I've just updated the title/description of this bug to reflect @digitaldogsbody's note that this is also an issue with records that are first created in Draft state.

**Comment by ashwinisukale** [comment] 2023-11-22 12:08
Yes @digitaldogsbody is correct, and this condition was added 3 year back.  
here are the details. 
https://github.com/datacite/lupo/commit/e8b157d06997ae8872d9cf4031341ff6396dde44

**Comment by ashwinisukale** [comment] 2023-11-23 08:26
We had discussion with kelly, here is requirement for event data state flow.

<img width="752" alt="event_data_state_flow" src="https://github.com/datacite/datacite/assets/1137325/ff92accf-bab3-4d8a-9873-d1ae8ddeec17">

**Comment by KellyStathis** [comment] 2023-11-23 19:22
Thanks @ashwinisukale!

It wouldn't hurt to have someone verify this (maybe @digitaldogsbody) - this was just my Zoom whiteboard attempt to map things out on the fly.

**Comment by wendelfabianchinsamy** [comment] 2023-11-24 08:49
@KellyStathis I was able to set up commons on my local machine and with it accessing the staging services I can confirm that this issue is reproducible. I will put together a couple of possible solution. @ashwinisukale and I will chat to @digitaldogsbody about these.

**Comment by digitaldogsbody** [comment] 2023-11-27 12:22
Registered -> Findable should always trigger a push to event data for processing, because the logic for parsing the metadata to find events sits in Levriero, and if the metadata had been updated several times in Lupo while the DOI remained in Registered state, we wouldn't necessarily have a guaranteed "dirty" attribute on the relevant fields to indicate that re-processing was required.

**Comment by digitaldogsbody** [comment] 2023-11-27 12:26
So, I think the flow should be:

Any state -> Published = Send to event data
Published + Changes to relevant fields = Send to event data
Published + Changes to other fields = Don't send to event data

The current code essentially does the latter two, and it is the lack of the first one that is causing the issue.

I think the boundary of responsibility from creating/deduplicating events should continue to lie with Levriero, and Lupo should not concern itself with whether particular events already exist or not when making a decision about whether to push a DOI to the queue or not.

**Comment by codycooperross** [comment] 2024-01-05 18:45
Reopening this since some events are still not being created properly. See this comment for more analysis: https://github.com/datacite/datacite/issues/1983#issuecomment-1875095237 

A similar issue was also reported for 10.57892/100-36, which was created with appropriate nameIdentifier metadata; however, no events or claims were created: 

- https://api.datacite.org/events?doi=10.57892/100-36 
- [https://profiles.datacite.org/admin/claims?utf8=✓&query="10.57892%2F100-36"](https://profiles.datacite.org/admin/claims?utf8=%E2%9C%93&query=%2210.57892%2F100-36%22)

**Comment by ashwinisukale** [comment] 2024-01-09 09:18
I created this DOI in direct finable state https://doi.stage.datacite.org/dois/10.82586%2F5krr-m803 ,

**Root Cause:** We are not passing the 'event' object while creating the DOI from UI. We are using state machine, if you pass event as `publish` then only it change the state from draft to findable. By default DOI has `draft` state. With draft state we do not fire any events.

```
irb(main):006:0> DataciteDoi.new(event: 'publish').state
=> "findable"
irb(main):007:0> DataciteDoi.new().state
=> "draft"
irb(main):008:0>
```


Cloudwatch link: https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:log-groups/log-group/$252Fecs$252Fclient-api-stage/log-events/ecs$252Fclient-api-stage$252F4d55ab675e914b15914fce5df1052a3e$3Fstart$3D-3600000$26filterPattern$3DEvent+Data+Import+Message 
```
2024-01-09T12:24:12.090+05:30

Copy
App 14227 output: 
{
    "message": "[Event Data Import Message] draft {\"id\"=>\"10.82586/5KRR-M803\", \"type\"=>\"dois\", \"attributes\"=>{\"doi\"=>\"10.82586/5KRR-M803\", \"state\"=>\"draft\", \"created\"=>Tue, 09 Jan 2024 06:54:11.000000000 UTC +00:00, \"updated\"=>Tue, 09 Jan 2024 06:54:11.000000000 UTC +00:00}} its a DOI",
    "@timestamp": "2024-01-09T06:54:11.624+00:00",
    "@version": "1",
    "severity": "INFO",
    "host": "ip-10-0-11-106.eu-west-1.compute.internal"
}
```

Here is input passed to the DataciteDoisController,  here we are not passing event as `'publish'`, instead it is `'null'` - ` "event": null`

```
App 14227 output: {
    "method": "POST",
    "path": "/dois",
    "format": "json",
    "controller": "DataciteDoisController",
    "action": "create",
    "status": 201,
    "duration": 126.33,
    "view": 0.47,
    "db": 10.88,
    "dd": {
        "trace_id": 4706096083433575302,
        "span_id": 3821487935634081952
    },
    "ddsource": [
        "ruby"
    ],
    "params": {
        "data": {
            "attributes": {
                "doi": "10.82586/5krr-m803",
                "confirmDoi": null,
                "url": "http://example.org",
                "creators": [
                    {
                        "name": "Ashwini-direct-findable",
                        "givenName": null,
                        "familyName": null,
                        "nameType": null,
                        "nameIdentifiers": [
                            {
                                "nameIdentifier": "Ashwini-direct-findable",
                                "nameIdentifierScheme": "Other",
                                "schemeUri": null
                            }
                        ],
                        "affiliation": []
                    }
                ],
                "titles": [
                    {
                        "title": "Ashwini-direct-findable",
                        "titleType": "Subtitle",
                        "lang": "mr"
                    }
                ],
                "publisher": "Ashwini-direct-findable",
                "publicationYear": 2024,
                "subjects": [],
                "contributors": [],
                "alternateIdentifiers": [],
                "dates": [],
                "language": null,
                "types": {
                    "resourceTypeGeneral": "Preprint"
                },
                "relatedIdentifiers": [],
                "sizes": [],
                "formats": [],
                "version": null,
                "rightsList": [],
                "descriptions": [],
                "geoLocations": [],
                "fundingReferences": [],
                "relatedItems": [],
                "xml": null,
                "schemaVersion": null,
                "source": "fabricaForm",
                "state": "draft",
                "reason": null,
                "event": null,
                "mode": "new"
            },
            "relationships": {
                "client": {
                    "data": {
                        "type": "repositories",
                        "id": "eldn.pbqvdv"
                    }
                }
            },
            "type": "dois"
        },
        "affiliation": "true",
        "datacite_doi": {}
    },
    "uid": "eldn.pbqvdv",
    "@timestamp": "2024-01-09T06:54:11.700+00:00",
    "@version": "1",
    "message": "[201] POST /dois (DataciteDoisController#create)",
    "severity": "INFO",
    "host": "ip-10-0-11-106.eu-west-1.compute.internal"
}
```

**Comment by ashwinisukale** [comment] 2024-01-09 09:33
So Doi which got directly created as `findable` still has a `draft` state in the DB, even if you update other attributes of that DOI, eg. I just added `related identifier` to the doi I created, it did not create any event, as its state in DB is still `draft`

**Comment by ashwinisukale** [comment] 2024-01-09 10:02
Apologies, I had created DOI but I was looking at wrong DOI. I will update my comment once I get full understanding. I deleted my previous comment, to avoid confusion.

**Comment by ashwinisukale** [comment] 2024-01-12 05:18
We have released the latest changes on staging and tested all the above cases. We can now see events for all the cases where we expect. @KellyStathis you can verify these changes once we release the changes to production. closing this ticket as are done with the fix and testing on staging.

**Closed** 2024-01-12 05:18 UTC
Labels: bug, issue::Event data creation and metadata population
